### PR TITLE
Add compiler-common to .gitmodules

### PR DESCRIPTION
**Pull request by victorb**
This includes squint-cljs/compiler-common in .gitmodules so it gets fetched if you do a recursive clone or otherwise init->update the submodules.

I'm guessing this is what was wanted, as `bb dev` expects the directory to exists, and the `Development` section in the readme.md file includes a `--recursive` flag but there is no submodules in the project until this commit.

Without having the directory cloned, `bb dev` fails with the following error message:

```
$ bb dev
shadow-cljs - config: /home/user/projects/squint-cljs/cherry/shadow-cljs.edn
shadow-cljs - starting via "clojure"
Error building classpath. Local lib io.github.squint-cljs/compiler-common not found: /home/user/projects/squint-cljs/cherry/compiler-common
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:
Data:     {:proc #object[java.lang.ProcessImpl 0x70fd331d "Process[pid=992892, exitValue=1]"], :exit 1, :in #object[java.lang.ProcessBuilder$NullOutputStream 0x73f6f91c "java.lang.ProcessBuilder$NullOutputStream@73f6f91c"], :out #object[java.lang.ProcessBuilder$NullInputStream 0xcf82f47 "java.lang.ProcessBuilder$NullInputStream@cf82f47"], :err #object[java.lang.ProcessBuilder$NullInputStream 0xcf82f47 "java.lang.ProcessBuilder$NullInputStream@cf82f47"], :prev nil, :cmd ["npx" "shadow-cljs" "--aliases" ":dev" "--config-merge" ".work/config-merge.edn" "watch" "cherry"], :type :babashka.process/error}
Location: /home/user/projects/squint-cljs/cherry/bb/tasks.clj:54:3

----- Context ------------------------------------------------------------------
50: (defn watch-cherry []
51:   (fs/delete-tree ".shadow-cljs/builds/clava/dev/ana/cherry")
52:   (fs/create-dirs ".work")
53:   (spit ".work/config-merge.edn" (shadow-extra-test-config))
54:   (shell "npx shadow-cljs --aliases :dev --config-merge .work/config-merge.edn watch cherry"))
      ^---
55:
56: (defn test-cherry []
57:   (fs/create-dirs ".work")
58:   (spit ".work/config-merge.edn" (shadow-extra-test-config))
59:   (shell "npm install")

----- Stack trace --------------------------------------------------------------
babashka.process/check                    - <built-in>
babashka.process/shell                    - <built-in>
tasks/watch-cherry                        - /home/user/projects/squint-cljs/cherry/bb/tasks.clj:54:3
tasks/watch-cherry                        - /home/user/projects/squint-cljs/cherry/bb/tasks.clj:50:1
user-a2f4f1ed-5634-4276-8768-39c52f8d8b49 - <expr>:26:1
```

### CODE REVIEW

**Comment by borkdude** [comment]
@victorb Sorry for the confusion. I removed the git submodule again since this caused trouble with distributing this library as a git dependency: tools deps doesn't support git deps. What I do locally for development now is clone the compiler-common repo inside the squint rep.

**Comment by victorb** [comment]
Ah, that's my bad.. Hm, if you're using tools.deps you should be able to use dependencies via git, as far as I know. Here is one example: https://clojure.org/guides/deps_and_cli#_using_git_libraries

I'm gonna close this regardless, since it doesn't apply. Maybe just adding the `git clone` command to the README.md would be enough then? It was just missing to have the directory for being able to setup the dev environment.

**Comment by borkdude** [comment]
You can use git libraries, but not git libraries that depend on git submodules.

**Comment by borkdude** [comment]
Feel free to update the docs

**Pull request closed without merging**
